language: node_js
node_js:
- '10'
services:
- mysql
env:
- NODE_ENV=test
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS not_citiesocial default character set utf8mb4
  collate utf8mb4_unicode_ci;'
- npm install sequelize-cli -g
- npm install mocha -g
before_script:
- sequelize db:migrate
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: ${{ env.HEROKU_API_KEY }}
  app: not-citiesocial
